# application-prod.yml

# 前端容器地址配置
app:
  cors:
    allowed-origins: http://124.222.132.163:2024/  # 使用前端容器名称和内部端口

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/online_shopping_mall?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: mzyudada
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none  # 生产环境建议使用 none，不自动更新数据库结构
    show-sql: false   # 生产环境建议关闭 SQL 日志

server:
  port: 8080

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: java_web.online_shopping_mall.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

# 日志配置
logging:
  level:
    root: INFO
    java_web.online_shopping_mall: INFO
  file:
    name: /var/log/online_mall/application.log