# 前端容器地址配置
app:
  cors:
    allowed-origins: http://localhost:5173


aliyun:
  oss:
    endpoint: your-endpoint
    access-key-id: your-access-key-id
    secret-access-key: your-secret-access-key
    bucket-name: your-bucket-name


spring:
  application:
    name: online_shopping_mall
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB



  datasource:
    url: jdbc:mysql://localhost:3306/online_shopping_mall
    username: root
    password: mzyudada
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    user:
      name: admin
      password: 123456

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package:
    - java_web.online_shopping_mall.entity   # 实体类包路径
    - java_web.online_shopping_mall.dto     # DTO 类包路径
    
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: java_web.online_shopping_mall.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto


jwt:
  secret: ta/K2kS3M9tvYPfBr5+PhpFvjYuHh54VqJdP1FQhGRM=
  expiration: 36000000



logging:
  level:
    root: info
    org.springframework: warn
    your.package.name: debug
